//
//  GamePresenter.swift
//  WordBuzzer
//
//  Created by Raheel Sadiq  on 09/02/2020.
//  Copyright (c) 2020 Raheel Sadiq . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GamePresentationLogic {
    func presentSomething(response: Game.Something.Response)
}

class GamePresenter: GamePresentationLogic {
    
    weak var viewController: GameDisplayLogic?
    
    // MARK: - Do something
    
    func presentSomething(response: Game.Something.Response) {
        let viewModel = Game.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
