//
//  GameModels.swift
//  WordBuzzer
//
//  Created by Raheel Sadiq  on 09/02/2020.
//  Copyright (c) 2020 Raheel Sadiq . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Game {

    struct Player {
        var score: Int
    }
    
    struct Round {
        let word: String
        let options: [String]
        let correctAnswer: [String]
    }
    
    
    struct Matct {
        let numberOfRounds: Int
        let rounds: [Round]
    }
    
    struct Word {
        let word: String
        let translation: String
    }
}
