//
//  GameWorker.swift
//  WordBuzzer
//
//  Created by Raheel Sadiq  on 09/02/2020.
//  Copyright (c) 2020 Raheel Sadiq . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class GameWorker {
    
    func fetchWords() -> [Game.Word] {
        
        var words = [Game.Word]()
        do {
            if let path = Bundle.main.path(forResource: "words", ofType: "json") {
                let data = try Data(contentsOf: URL(fileURLWithPath: path), options: .mappedIfSafe)
                let jsonResult = try JSONSerialization.jsonObject(with: data, options: .mutableLeaves)
                if let jsonResult = jsonResult as? [[String: AnyObject]] {
                    
                    for dict in jsonResult {
                        words.append(
                            Game.Word(
                                word: dict["text_eng"] as! String,
                                translation: dict["text_spa"] as! String
                            )
                        )
                    }
                }
                
                return words
            }
        } catch {
            print(error.localizedDescription)
            return words
        }
        
        return words
        
    }
}
