//
//  GameViewController.swift
//  WordBuzzer
//
//  Created by Raheel Sadiq  on 09/02/2020.
//  Copyright (c) 2020 Raheel Sadiq . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GameDisplayLogic: class {

}
  
class GameViewController: UIViewController, GameDisplayLogic {
    
    
    // IBOutlet
    
    @IBOutlet weak var startMatchButton: UIButton!{
        didSet{
            startMatchButton.titleLabel?.numberOfLines = 2
            startMatchButton.titleLabel?.textAlignment = .center
            startMatchButton.setRoundedFull()
        }
    }
    
    var interactor: GameBusinessLogic?
    var router: (NSObjectProtocol & GameRoutingLogic & GameDataPassing)?
    
    // MARK: - Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: - Setup
    
    private func setup() {
        let viewController = self
        let interactor = GameInteractor()
        let presenter = GamePresenter()
        let router = GameRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: - Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        interactor?.startMatch()
    }
    
    
    // MARK: - Display


    
    // MARK: - IBActions

    @IBAction func startMatch(){
        interactor?.startMatch()
    }
    
}
