//
//  GamePresenter.swift
//  WordBuzzer
//
//  Created by Raheel Sadiq  on 09/02/2020.
//  Copyright (c) 2020 Raheel Sadiq . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GamePresentationLogic {
    func present(round: Game.Round)
    func presentRoundResult(playerNumber: Int, hasWon: Bool)
    func presentPlayer(players: [Game.Player])
    func presentWinner(player: Game.Player)
    func presentDraw()
}

class GamePresenter: GamePresentationLogic {
    
    weak var viewController: GameDisplayLogic?
   
    private var timer: Timer?
    private var round: Game.Round!
    private var currentOptionIndex: Int = 0
    
    func presentPlayer(players: [Game.Player]) {
        var playerViewModels = [Game.PlayerViewModel]()
        for (index,player) in players.enumerated() {
            playerViewModels.append(Game.PlayerViewModel(title: "Player \(index + 1)\n score: \(player.score)"))
        }
        
        viewController?.update(players: playerViewModels)
    }
    
    func present(round: Game.Round) {
        timer?.invalidate()
        self.round = round
        viewController?.displayBoardWith(round: round)
        presentNextOption()
    }
    
    private func startTimer(){
        timer = Timer.scheduledTimer(withTimeInterval: round.time, repeats: false, block: { [weak self](timer) in
            self?.presentNextOption()
            })
    }
    
    @objc func presentNextOption(){
        viewController?.display(option: round.options[currentOptionIndex])
        currentOptionIndex += 1
        if currentOptionIndex == round.options.count {
            currentOptionIndex = 0
        }
        startTimer()
    }

    func presentRoundResult(playerNumber: Int, hasWon: Bool) {
        viewController?.displayRoundResult(playerNumber: playerNumber, isWinner: hasWon)
    }
    
    func presentWinner(player: Game.Player) {
        viewController?.displayWinner()
    }
    
    func presentDraw() {
        viewController?.displayMatchDraw()
    }
}
