//
//  GameViewController.swift
//  WordBuzzer
//
//  Created by Raheel Sadiq  on 09/02/2020.
//  Copyright (c) 2020 Raheel Sadiq . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GameDisplayLogic: class {
    func displayBoardWith(round: Game.Round)
    func displayRoundResult(playerNumber: Int, isWinner: Bool)
    func display(option: String)
    func update(players:[Game.PlayerViewModel])
    func displayMatchDraw()
    func displayWinner()
}
  
class GameViewController: UIViewController, GameDisplayLogic {
    
    @IBOutlet var playerButtons: [PlayerButton]!
    
    @IBOutlet weak var gameBoardView: UIView!{
        didSet {
            gameBoardView.isHidden = true
        }
    }
    @IBOutlet weak var wordLabel: UILabel!
    @IBOutlet weak var optionLabel: UILabel! {
        didSet{
            optionLabel.textColor = UIColor.General.SteelBlue
        }
    }

    // IBOutlet
    
    @IBOutlet weak var startMatchButton: UIButton!{
        didSet{
            startMatchButton.titleLabel?.numberOfLines = 2
            startMatchButton.titleLabel?.textAlignment = .center
            startMatchButton.setRoundedFull()
        }
    }
    
    var interactor: GameBusinessLogic?
    var router: (NSObjectProtocol & GameRoutingLogic & GameDataPassing)?
    
    // MARK: - Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: - Setup
    
    private func setup() {
        let viewController = self
        let interactor = GameInteractor()
        let presenter = GamePresenter()
        let router = GameRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: - Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()

        UIView.animateKeyframes(withDuration: 1, delay: 0, options: [UIView.KeyframeAnimationOptions(rawValue: UIView.AnimationOptions.repeat.rawValue), UIView.KeyframeAnimationOptions(rawValue: UIView.KeyframeAnimationOptions.RawValue(UIView.AnimationCurve.easeInOut.rawValue)), UIView.KeyframeAnimationOptions(rawValue: UIView.AnimationOptions.autoreverse.rawValue)] , animations: {
            self.optionLabel.alpha = 0.5
        }) { finished in
        }
    }
    
    
    // MARK: - Display

    func displayBoardWith(round: Game.Round){
        
        gameBoardView.showWithAnimation()
        startMatchButton.hideWithAnimation()
        wordLabel.text = round.word
        
        for button in playerButtons {
            button.gameState = .normal
        }
    }
    
    func displayRoundResult(playerNumber: Int, isWinner: Bool){
        if isWinner {
            playerButtons[playerNumber].gameState = .won
        }else{
            playerButtons[playerNumber].gameState = .lost
        }
    }
    
    func update(players: [Game.PlayerViewModel]) {
        for (index, player) in players.enumerated() {
            playerButtons[index].setTitle(player.title, for: .normal)
        }
    }
    
    func displayMatchDraw() {
        gameBoardView.hideWithAnimation()
        startMatchButton.showWithAnimation()
        startMatchButton.setTitle("Match Draw\nRematch?", for: .normal)
    }
    
    func display(option: String) {
        
        displayedOption = option
        
        UIView.animate(withDuration: 0.2, animations: { [weak self]() -> Void in
            self?.optionLabel.alpha = 0
        }, completion: { [weak self] (finishes) -> Void in
            if finishes {
                self?.optionLabel.text = option
                UIView.animate(withDuration: 0.2, animations: { [weak self]() -> Void in
                    self?.optionLabel.alpha = 1
                }, completion: nil)
            }
        })
    }
    
    private var displayedOption: String?

    func displayWinner() {
        performSegue(withIdentifier: "Result", sender: nil)
        gameBoardView.hideWithAnimation()
        startMatchButton.showWithAnimation()
        startMatchButton.setTitle("Rematch?", for: .normal)
    }
    
    // MARK: - IBActions

    @IBAction func startMatch(){
        interactor?.startMatch()
    }
    
    @IBAction func playerBuzzAction(sender: UIButton) {
        interactor?.selected(option: displayedOption! , by: sender.tag)
    }
}
