//
//  GameInteractor.swift
//  WordBuzzer
//
//  Created by Raheel Sadiq  on 09/02/2020.
//  Copyright (c) 2020 Raheel Sadiq . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GameBusinessLogic {
    func startMatch()
    func selected(option: String, by playerNumber: Int)
    func timedOut()
}

protocol GameDataStore {
    var winnerTitle: String {get set}
}

class GameInteractor: GameBusinessLogic, GameDataStore {
    
    var presenter: GamePresentationLogic?
    var worker: GameWorker
    var words = [Game.Word]()
    var players: [Game.Player]!
    var match: Game.Matct!
    let numberOfRounds = 3
    let numberOfOptions = 4
    let timeInterval = TimeInterval(3)
    var winnerTitle: String  = ""
    
    var currentRound: Int = -1 {
        didSet{
            presenter?.presentPlayer(players: players)
            presenter?.present(round: match.rounds[currentRound])
        }
    }

    init() {
        worker = GameWorker()
        words = worker.fetchWords()
    }
    
    func startMatch() {
        
        players = [
            Game.Player(score: 0),
            Game.Player(score: 0),
            Game.Player(score: 0),
            Game.Player(score: 0)
        ]
        
        var rounds = [Game.Round]()
        
        for _ in 0..<numberOfRounds {
            
            let randomWords = words.choose(numberOfOptions)
            let options = randomWords.map { (word) -> String in
                word.translation
            }
            
            let round = Game.Round(
                word: randomWords.first!.word,
                correctAnswer: randomWords.first!.translation,
                options: options.shuffled(),
                time: timeInterval)
            rounds.append(round)
        }
        
        match = Game.Matct(
            numberOfRounds: numberOfRounds,
            rounds: rounds)
        currentRound = 0
    }
    
    func selected(option: String, by playerNumber: Int) {
        
        let round = match.rounds[currentRound]

        if option == round.correctAnswer {
            presenter?.presentRoundResult(playerNumber: playerNumber, hasWon: true)
            players[playerNumber].score  += 1
        }else{
            presenter?.presentRoundResult(playerNumber: playerNumber, hasWon: false)
        }
        
        if currentRound == numberOfRounds-1 {
            if let winner = players.max(by: { $0.score < $1.score }), winner.score > 0 {
                winnerTitle = "Player \(playerNumber + 1)"
                presenter?.presentWinner(player: winner)
                
            }else {
                presenter?.presentDraw()
            }

        }else{
            currentRound += 1
        }
    }
    
    func timedOut(){
        // time out if no one answers
    }
}


